@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.flechazo.nekoration.client.rendering.entities;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;