@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.flechazo.nekoration.entities;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;